pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo "building..."
            }
        }
        stage('Test') {
            steps {
                echo "testing..."
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo "delivering..."
            }
        }
    }
}
